import type { Metadata } from 'next'
import { Providers } from './providers'
import "../styles/globals.css";
import { Box, ColorModeScript } from '@chakra-ui/react';
import { geomanist } from '@/fonts';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import { theme } from './theme';
 


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={geomanist.className}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Providers>
          <Navbar />
          <Box as="main" minH={"100vh"}>
            {children}
          </Box>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
